#!/bin/bash
# Not meant to be portable: mostly for documentation purposes.
# Stores build artiacts one directory above the root repository directory.
# Builds to ../build
# Installs to ../install

(
    set -euo pipefail
    REPO_DIR="$(readlink -f $(dirname $0))"
    REPO_NAME="$(basename ${REPO_DIR})"
    BUILD_DIR="$(dirname ${REPO_DIR})/build"
    INSTALL_DIR="$(dirname ${REPO_DIR})/install"

    mkdir -p ${BUILD_DIR} ${INSTALL_DIR}

    cmake \
        -G "Ninja" \
        -B "${BUILD_DIR}" \
        -S "${REPO_DIR}" \
        -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}

    cmake --build "${BUILD_DIR}" \
        --parallel $(nproc) \
        --target install
)
